### ISSUE TITLE
Add scheme to the route configuration.

### ISSUE THREAD

**Issue by shochdoerfer** [bitExpert/pathfinder#1]
Should we add the scheme to the route configuration or is it enough to filter routes based on their method? Does it make sense to distinguish between routes for different schemes?

**Comment by dropdevcoding** [comment]
A use case for a scheme aware route would be login and redirect to https if requested via http, but I also could imagine a middleware for handling those kind of redirections for a configurable set of route identifiers.

**Comment by shochdoerfer** [comment]
In that particular case a middleware might be the better solution. It might be a way to force https on the user/client, but then again a middleware would also solve this way better ;)

**Comment by dropdevcoding** [comment]
Yeah, that's right since any kind of security doesn't belong to routing at all - So if nobody has another opinion we may close this discussion.
