### ISSUE TITLE
Enrich documentation with different use cases

### ISSUE THREAD

**Issue by dropdevcoding** [bitExpert/pathfinder#3]
Since the route offers different kinds of configuration possibilities and the router may deal with whatever you want as target (actiontokens, arrayified callable definitions, callables...) we should explain how to deal with the several cases and show some examples. It would also be helpful to show how to implement your own matcher.

@geekishmatt: Do you want to take on that task? If you get stuck, you'll may ask me for help of course :-)

**Comment by geekishmatt** [comment]
@peterhildenbrand 

I have enriched the documentation (+ fixed the Matcher's PHPDoc) but somehow the remote set-url origin was set to bitexpert/pathfinder instead to geekishmatt/pathfinder.

Is there a possibility to revert the revision back to 659e69dd476ce4468a7bf35296ce1b1532a63d1b (2 commits)?

**Comment by shochdoerfer** [comment]
Leave it as it is. I do not want to rewrite history, otherwise things may break.

**Comment by geekishmatt** [comment]
@shochdoerfer  Alrighty then.
@peterhildenbrand Anything else to do?

**Comment by dropdevcoding** [comment]
I commented on your pull request but now I can't see it anymore. Do you have any clue why @shochdoerfer ?

**Comment by shochdoerfer** [comment]
@geekishmatt anything to be done or can we close the issue?
